### ISSUE TITLE
Reconnection issues

### ISSUE THREAD

**Issue by joshcoales** [joshcoales/Hallo#147]
> [07:22:25] [canternet] PONG
> [07:22:39] [shadowworld] #ecco-the-dolphin < c000242> I JUST NOTICE IT IS GONE WHEN I WANT TO USE IT
> [07:22:52] [psigenix] PING
> [07:22:52] [psigenix] PONG
> [07:22:54] [shadowworld] #ecco-the-dolphin < deer-spangle> YEAH
> [07:23:13] [shadowworld] PING
> [07:23:13] [shadowworld] PONG
> Server disconnected. Reconnecting.
> [07:24:18] waiting for first message from server: shadowworld
> [07:24:18] sending nick and user info to server: shadowworld
> [07:24:18] [shadowworld] Unhandled data: E:moroso.ILUdowWorOTICEUTH Look up yoe...
> [07:24:18] [shadowworld] Unhandled data: NOTI AUTH Checkent
> [07:24:19] [shadowworld] Unhandled data: mroso.hadowWoNOTICE AUT No Ident re
> [07:24:19] [shadowworld] Unhandled data: mro.IL.ShWorl01alWelcome to thadowWor IetrkalloHaBotilr.cswaac.u
> :moso.UShowrlNe00Hao ouho imosoL..ShawWor.N, nn vsi bam-2.7:msoL.US.adowrlNe00Hao hiseerasreedueov01at1:9 CmosoL.UShadoor.Net04al mosILS.adowWldetahut.0 acCfFiIjkKmnoOrxXAbjkmMOprRsv
> [07:24:19] [shadowworld] Unhandled data: .NeHNETWK=adowrlSALI MBA=2 MCHNE=1CHNEEN2 CKN=7 CKN= TICLE30MOS=CHTYS=CHLIT=10REFIX=v) STUSG=@:a aab ts rv
> [07:24:19] [shadowworld] Unhandled data: ShwWetHao SEPPG=ciAT=1 ESTmnANDEbeI,jlimOpsSt XLT=200,e:0,10TAMAX=CAOW:,KI:4ILL:,NIC0,RTPRMS20,Wlable on this server
> [07:24:19] [shadowworld] Unhandled data: rld. 2allo he a 1useran81nvib o5 rvsmoro.IUShadowrlNe25Hal 1:I Orato oin
> :ro.IUShawWor.N 2 Hlo3 haelfo
> :ro.IUShadoor.N 2 HloI ve7 ies d 1 rvsmoro.IUShawWldet65al :rrentoc urs27 Ma 513:mor.IUShawWldet66al :rrt ob urs97ax63
> :roso.IL.US.ShowrlNet NOTICE Hlo**Noce- tdasaschge01210mosoL..Sdoor.N 3 Hlo- ro.IUShawWldetesgef e y
> [07:24:19] [shadowworld] Unhandled data: o2 H :-9/1001210mosoL..Sdoorld.Net 372 ll:-  =========================================
> [07:24:19] [shadowworld] Unhandled data: 2 Ho o..UShowrlNe37Hao     lce  t Sdoor I Nwo   -  IRShowrlNE
> :ro.IUShaor.N 3 H-   oro..UShowrlNe              08000.
> [07:24:19] [shadowworld] Unhandled data: adowWoall-  mosoL..Sdoor.N 3 Hlo-  -===================================
> :ro.IL.UShNe37Hao  .IShowrlNe37Hao :-                __ _ ____
> :ro.IUShadWod.t 2 ll:-           '_ ` \ / |___  _/ \
> [07:24:19] [shadowworld] Unhandled data:         | | | ) __) |
> [07:24:19] [shadowworld] Unhandled data: .IL..SdowWorlNe :            | | |_/|  _/|_/__  :moroIL.US.SdowWor.Net 3 Hlo :-             :moroso.IL.US.ShadowWorld.Net 372 Hallo :-
> [07:24:19] [shadowworld] Numeric server info: :moroso.IL.US.ShadowWorld.Net 372 Hallo :-    -=======================================================================-
> [07:24:19] [shadowworld] Numeric server info: :moroso.IL.US.ShadowWorld.Net 372 Hallo :-
> [07:24:19] [shadowworld] Numeric server info: :moroso.IL.US.ShadowWorld.Net 372 Hallo :-      Network Administrators    --   Spottie     -- spottie@shadowworld.net
> [07:24:19] [shadowworld] Numeric server info: :moroso.IL.US.ShadowWorld.Net 372 Hallo :-                                --   DAEMON      -- daemon@shadowworld.net
> [07:24:19] [shadowworld] Numeric server info: :moroso.IL.US.ShadowWorld.Net 372 Hallo :-
> ...
> [07:24:19] [shadowworld] Numeric server info: :moroso.IL.US.ShadowWorld.Net 372 Hallo :-      be alarmed if your firewall software reports a port scan from this
> [07:24:19] [shadowworld] Numeric server info: :moroso.IL.US.ShadowWorld.Net 372 Hallo :-      machine (irc.emarhavil.com or 208.100.30.94).  Please  e-mail  the
> [07:24:19] [shadowworld] Numeric server info: :moroso.IL.US.ShadowWorld.Net 372 Hallo :-      above listed administrator if you have any questions.
> [07:24:19] [shadowworld] Numeric server info: :moroso.IL.US.ShadowWorld.Net 372 Hallo :-
> [07:24:19] [shadowworld] Numeric server info: :moroso.IL.US.ShadowWorld.Net 372 Hallo :-    -=======================================================================-
> [07:24:19] [shadowworld] Numeric server info: :moroso.IL.US.ShadowWorld.Net 372 Hallo :-
> Exception in thread Thread-1:
> Traceback (most recent call last):
>   File "/home/alumni/drspangle/Hallo/Server.py", line 1047, in read_line_from_socket
>     next_byte = self._socket.recv(1)
> socket.error: [Errno 110] Connection timed out
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/alumni/drspangle/Hallo/Server.py", line 424, in run
>     next_line = self.read_line_from_socket()
>   File "/home/alumni/drspangle/Hallo/Server.py", line 1050, in read_line_from_socket
>     raise ServerException
> Server.ServerException
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/lib/python3.2/threading.py", line 740, in _bootstrap_inner
>     self.run()
>   File "/usr/lib/python3.2/threading.py", line 693, in run
>     self._target(_self._args, *_self._kwargs)
>   File "/home/alumni/drspangle/Hallo/Server.py", line 428, in run
>     self.reconnect()
>   File "/home/alumni/drspangle/Hallo/Server.py", line 413, in reconnect
>     self.connect()
>   File "/home/alumni/drspangle/Hallo/Server.py", line 333, in connect
>     self.raw_connect()
>   File "/home/alumni/drspangle/Hallo/Server.py", line 372, in raw_connect
>     if len(next_welcome_line.split()[1]) == 3 and next_welcome_line.split()[1].isdigit():
> IndexError: list index out of range
> 
> [07:24:19] [shadowworld] Numeric server info: :moroso.IL.US.ShadowWorld.Net 372 Hallo :-      \*  For a list of available servers on this network, type  /LINKS
> [07:24:19] [shadowworld] Numeric server info: :moroso.IL.US.ShadowWorld.Net 372 Hallo :-      \*  For a list of available channels on this network, type  /LIST
> [07:24:19] [shadowworld] Numeric server info: :moroso.IL.US.ShadowWorld.Net 372 Hallo :-      \*  For general IRC help, type  /JOIN #help  or  /JOIN #shadow
> [07:24:19] [shadowworld] Numeric server info: :moroso.IL.US.ShadowWorld.Net 372 Hallo :-      \*  For IRC Operator assistance, type  /JOIN #shadow
> [07:24:19] [shadowworld] Numeric server info: :moroso.IL.US.ShadowWorld.Net 372 Hallo :-
> [07:24:19] [shadowworld] Numeric server info: :moroso.IL.US.ShadowWorld.Net 372 Hallo :-    -=======================================================================-

This is after a timeout from shadowworld, which I solved with

> 07:07:21 < deer-spangle> Hallo: connect shadowworld
> 07:07:23 <&Hallo> Already connected to that server
> 07:07:28 < deer-spangle> Hallo: disconnect shadowworld
> 07:07:29 <&Hallo> Disconnected from server: shadowworld.
> 07:07:32 < deer-spangle> Hallo: connect shadowworld
> 07:07:33 <&Hallo> Connected to server: shadowworld.

But looks like a second thread was made connecting to the server, which the original thread then conflicted with after restarting itself

**Comment by joshcoales** [comment]
I think this will get solved by this:
https://github.com/joshcoales/Hallo/pull/159
but uncertain.

**Comment by joshcoales** [comment]
This is either solved, or just better stability https://trello.com/c/uJM69baD/5-better-irc-server-connection-stability
